### ISSUE TITLE
follow the readme cannot work

### ISSUE THREAD

**Issue by fenglixa** [HazyResearch/evaporate#2]
The steps in the readme file are not clear, and some errors with following the steps:

After run `bash run.sh`
Report error:
```
Cannot import name 'Manifest' from 'manifest'
```

**Comment by simran-arora** [comment]
Hi thanks for your note. Did you install manifest already?

**Comment by fenglixa** [comment]
Yes, I installed it, followed the steps as below:
```
git clone git@github.com:HazyResearch/evaporate.git
cd evaporate
# pip install -r requirements.txt

# Weak supervision code
cd metal-evap
git submodule init
git submodule update
pip install -e .

# Manifest 
git clone git@github.com:HazyResearch/manifest.git
cd manifest
pip install -e .

git lfs install
git clone https://huggingface.co/datasets/hazyresearch/evaporate

bash run.sh
```

And report error as below:
```
bash run.sh
Traceback (most recent call last):
  File "run_profiler.py", line 11, in <module>
    from utils import get_structure, get_manifest_sessions, get_file_attribute
  File "/root/test/evaporate/utils.py", line 5, in <module>
    from manifest import Manifest
ImportError: cannot import name 'Manifest' from 'manifest' (unknown location)
Traceback (most recent call last):
  File "run_profiler.py", line 11, in <module>
    from utils import get_structure, get_manifest_sessions, get_file_attribute
  File "/root/test/evaporate/utils.py", line 5, in <module>
    from manifest import Manifest
ImportError: cannot import name 'Manifest' from 'manifest' (unknown location)
```

**Comment by simran-arora** [comment]
Did the pull request fix your issue? It seems like manifest is running for you now?

**Comment by fenglixa** [comment]
Yeah, let's close this issue now. Thanks!
/close

**Comment by fenglixa** [comment]
Open again to trace the readme file still need to be updated.  e.g. the requirement.txt file is not exist.
Maybe later, I could have some inputs.

**Comment by simran-arora** [comment]
Ah good catch, I've updated the README. Let me know if you still run into issues and thanks for your help

**Comment by fenglixa** [comment]
Thanks @simran-arora 
/Close this issue

**Comment by raywgs** [comment]
hey how did you fix the Cannot import name 'Manifest' from 'manifest' issue?
