### ISSUE TITLE
what library of manifest is evaporate suppose to be using?

### ISSUE THREAD

**Issue by brando90** [HazyResearch/evaporate#26]
I think this is not present in either the src install of manifest or manifest-ml from pypi
```
Traceback (most recent call last):
  File "/lfs/ampere1/0/brando9/evaporate/evaporate/run_profiler.py", line 477, in <module>
    main()
  File "/lfs/ampere1/0/brando9/evaporate/evaporate/run_profiler.py", line 473, in main
    run_experiment(profiler_args)
  File "/lfs/ampere1/0/brando9/evaporate/evaporate/run_profiler.py", line 237, in run_experiment
    file2chunks, file2contents, manifest_sessions = prepare_data(
  File "/lfs/ampere1/0/brando9/evaporate/evaporate/run_profiler.py", line 64, in prepare_data
    manifest_sessions = get_manifest_sessions(profiler_args.MODELS, MODEL2URL=profiler_args.MODEL2URL, KEYS=profiler_args.KEYS)
  File "/afs/cs.stanford.edu/u/brando9/evaporate/evaporate/utils.py", line 149, in get_manifest_sessions
    manifest, model_name = get_manifest_session(
  File "/afs/cs.stanford.edu/u/brando9/evaporate/evaporate/utils.py", line 211, in get_manifest_session
    params = manifest.client_pool.get_client().get_model_params()
AttributeError: 'ClientConnectionPool' object has no attribute 'get_client'. Did you mean: 'num_clients'?
```

trying to debug it right now.

**Comment by brando90** [comment]
seems that manifest-ml not source worked.

I recommend not putting the manifest src instructions in the current way, it looks like install from src is a req.

**Comment by xiaohaoxing** [comment]
I debugged and replaced this function with `get_current_client()`.
