### ISSUE TITLE
AttributeError: 'Manifest' object has no attribute 'client'

### ISSUE THREAD

**Issue by fenglixa** [HazyResearch/evaporate#3]
As error below, could someone help? Thanks:
```
(.venv9) fenglixa evaporate/src ‹main*› » bash run.sh
Data lake
Traceback (most recent call last):
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 476, in <module>
    main()
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 472, in main
    run_experiment(profiler_args)
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 237, in run_experiment
    file2chunks, file2contents, manifest_sessions = prepare_data(
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 64, in prepare_data
    manifest_sessions = get_manifest_sessions(profiler_args.MODELS, MODEL2URL=profiler_args.MODEL2URL, KEYS=profiler_args.KEYS)
  File "/Users/lifeng/go/src/github.com/evaporate/src/utils.py", line 145, in get_manifest_sessions
    manifest, model_name = get_manifest_session(
  File "/Users/lifeng/go/src/github.com/evaporate/src/utils.py", line 205, in get_manifest_session
    params = manifest.client.get_model_params()
AttributeError: 'Manifest' object has no attribute 'client'
Data lake
Traceback (most recent call last):
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 476, in <module>
    main()
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 472, in main
    run_experiment(profiler_args)
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 237, in run_experiment
    file2chunks, file2contents, manifest_sessions = prepare_data(
  File "/Users/lifeng/go/src/github.com/evaporate/src/run_profiler.py", line 64, in prepare_data
    manifest_sessions = get_manifest_sessions(profiler_args.MODELS, MODEL2URL=profiler_args.MODEL2URL, KEYS=profiler_args.KEYS)
  File "/Users/lifeng/go/src/github.com/evaporate/src/utils.py", line 145, in get_manifest_sessions
    manifest, model_name = get_manifest_session(
  File "/Users/lifeng/go/src/github.com/evaporate/src/utils.py", line 205, in get_manifest_session
    params = manifest.client.get_model_params()
AttributeError: 'Manifest' object has no attribute 'client'
```

**Comment by fenglixa** [comment]
```
(evaporate) root@itzvsi-310001mfhm-tfq4zta3:~/test/evaporate/manifest# python
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from manifest import Manifest
>>> manifest = Manifest(
...     client_name = "huggingface",
...     client_connection = "http://127.0.0.1:5000",
... )
>>> print(manifest.client.get_model_params())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Manifest' object has no attribute 'client'    -----> this error
```
